AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'

Lint/MissingSuper:
  Exclude:
    - 'app/interactors/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false